"use client";
import { Inter } from "next/font/google";
import "../globals.css";
// import Provider from "../_componnets/Provider";
const inter = Inter({ subsets: ["greek-ext"] });
import Topbar2 from "../_componnets/Topbar2";
import ListRouts from "../_componnets/listRouts";
import { UseGlobalState } from "../Context/GlobalContext";
// export const metadata = {
//   title: "hello chat App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { user, listopbar, setlisttopbar } = UseGlobalState();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar2 />
        {children}
      </body>
    </html>
  );
}
