"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./Context/GlobalContext";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
import { Toaster, toast } from "sonner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/react";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ height: "100vh", width: "100vw" }}
      >
        <NextUIProvider>
          <GlobalProvider>{children} </GlobalProvider>
          <ToastContainer />
        </NextUIProvider>
      </body>
    </html>
  );
}
