import { Inter } from "next/font/google";
import "../globals.css";
// import ToastContext from "../_componnets/ToastContext";
// import Provider from "../_componnets/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "auth hello chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-purple-600`}>
        {/* <Provider> */}
        {/* <ToastContext /> */}
        {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
